# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tUf-WefP0RypXjKjRkbXv1ecrcYa48pc
"""

import pandas as pd

df = pd.read_csv("/content/sample_data/mnist_test.csv")

df.head()

print("Satrlar soni:", df.shape[0])
print("Ustunlar soni:", df.shape[1])

df_clean = df.dropna()  # NaN (bo‘sh) satrlarni o‘chiradi

deleted_rows = df.shape[0] - df_clean.shape[0]
print("O'chgan satrlar soni:", deleted_rows)

df_clean.head()  # Tozalangan jadvalning birinchi 5 satri

# 'label' ustuni bo‘yicha guruhlab, piksel qiymatlari o'rtachasini chiqaramiz
grouped = df.groupby(df.columns[0]).mean()
print(grouped)